
export const response = [
	["name", "city"],
	["Varun", "India"],
	["Tejas", "Dubai"],
	["Vish", "Canada"],
	["Don", "new york"],
	["Rahul", "India"],
	["American", "Dubai"],
	["Wow", "Canada"],
	["Love", "new york"],
	["Lord", "India"],
	["Every", "Dubai"],
	["Edit", "Canada"],
	["Happy", "new york"],
	["Awesome", "India"],
	["Some", "Dubai"],
	["Here", "Canada"],
	["Down", "new york"],
	["Upward", "India"],
	["TopMost", "Dubai"],
	["LikeMost", "Canada"],
	["Popular", "new york"],
	["SecLast", "India"],
	["Last", "Dubai"],
];
